name = "bandlings-chat"
main = "worker.js"
compatibility_date = "2026-06-13"
workers_dev = false

routes = [
  { pattern = "game-factory.tech/api/bandlings-chat*", zone_name = "game-factory.tech" }
]

[[kv_namespaces]]
binding = "VOTES"
id = "77b47ed18e7549dcb26673a3f834619e"
