import { supabaseRequest } from './supabase.js';

export const MEGATON_PAID_GACHA_CATALOG_VERSION = 'megaton-paid-gacha-v1-2026-08-01';

const RARITIES = Object.freeze(['common', 'rare', 'epic', 'legendary', 'mythic']);
const BOOSTS = Object.freeze([
  ['caps_mult', 'Caps gain'],
  ['yield_mult', 'Blast yield'],
  ['cost_disc', 'Upgrade discount'],
  ['crit_bonus', 'Extra income'],
  ['offline_mult', 'Reactor gain'],
  ['nuke_cost_disc', 'Nuke discount'],
  ['daily_mult', 'Daily ration'],
  ['ship_bonus', 'Ship bonus'],
]);
const BASE_COLLECTIBLES = Object.freeze([
  ['common_rust_dart', 'Rust Dart', 'common', 'caps_mult'],
  ['common_caution_capsule', 'Caution Capsule', 'common', 'nuke_cost_disc'],
  ['common_scrap_courier', 'Scrap Courier', 'common', 'offline_mult'],
  ['common_coolant_cell', 'Coolant Cell', 'common', 'yield_mult'],
  ['common_smoke_loop', 'Smoke Loop', 'common', 'crit_bonus'],
  ['common_bottlecap_buddy', 'Bottlecap Buddy', 'common', 'daily_mult'],
  ['common_barrel_imp', 'Barrel Imp', 'common', 'ship_bonus'],
  ['common_prize_crate', 'Prize Crate', 'common', 'caps_mult'],
  ['rare_sky_needle', 'Sky Needle', 'rare', 'yield_mult'],
  ['rare_triwing_courier', 'Triwing Courier', 'rare', 'offline_mult'],
  ['rare_blue_plasma_core', 'Blue Plasma Core', 'rare', 'crit_bonus'],
  ['rare_chaff_bloom', 'Chaff Bloom', 'rare', 'nuke_cost_disc'],
  ['rare_glow_slime', 'Glow Slime', 'rare', 'ship_bonus'],
  ['rare_orbital_bolt', 'Orbital Bolt', 'rare', 'yield_mult'],
  ['rare_sparkler_payload', 'Sparkler Payload', 'rare', 'daily_mult'],
  ['epic_splitter_pod', 'Splitter Pod', 'epic', 'yield_mult'],
  ['epic_neon_guard_drone', 'Neon Guard Drone', 'epic', 'crit_bonus'],
  ['epic_bubblegum_core', 'Bubblegum Core', 'epic', 'offline_mult'],
  ['epic_glass_comet', 'Glass Comet', 'epic', 'nuke_cost_disc'],
  ['epic_hazard_mascot', 'Hazard Mascot', 'epic', 'caps_mult'],
  ['legendary_sun_crown', 'Sun Crown', 'legendary', 'yield_mult'],
  ['legendary_blackbox_rod', 'Blackbox Rod', 'legendary', 'crit_bonus'],
  ['legendary_prism_fission', 'Prism Fission', 'legendary', 'caps_mult'],
  ['mythic_last_button', 'Last Button', 'mythic', 'yield_mult'],
]);
const RARITY_COUNTS = Object.freeze({ common: 55, rare: 25, epic: 14, legendary: 5, mythic: 1 });
const RARITY_VALUES = Object.freeze({
  common: Object.freeze([0.005, 0.0075, 0.01]),
  rare: Object.freeze([0.014, 0.017, 0.02]),
  epic: Object.freeze([0.026, 0.03, 0.034]),
  legendary: Object.freeze([0.045, 0.05, 0.055]),
  mythic: Object.freeze([0.07]),
});
const ROMAN = Object.freeze(['I', 'II', 'III', 'IV', 'V']);

function pad3(value) {
  return String(value).padStart(3, '0');
}

function buildCatalog() {
  const out = [];
  for (const rarity of RARITIES) {
    const seeds = BASE_COLLECTIBLES.filter((row) => row[2] === rarity);
    for (let ordinal = 0; ordinal < RARITY_COUNTS[rarity]; ordinal += 1) {
      const [baseId, baseName, , baseBoostKind] = seeds[ordinal % seeds.length];
      const suffix = ordinal < seeds.length ? '' : pad3(ordinal + 1);
      const baseBoostIndex = BOOSTS.findIndex((boost) => boost[0] === baseBoostKind);
      const boost = BOOSTS[(ordinal + baseBoostIndex) % BOOSTS.length] || BOOSTS[0];
      const values = RARITY_VALUES[rarity];
      out.push(Object.freeze({
        id: suffix ? `${baseId}_${suffix}` : baseId,
        name: suffix ? `${baseName} Mk ${ROMAN[(ordinal - 1) % ROMAN.length]}` : baseName,
        rarity,
        boost: Object.freeze({
          kind: boost[0],
          label: boost[1],
          value: values[ordinal % values.length],
        }),
      }));
    }
  }
  return Object.freeze(out);
}

// This is a compact server-side projection of the canonical catalog generated by
// Games/211_megaton/src/platforms/telegram/js/collectibles.js. IDs, rarity counts,
// names and boost rotation intentionally mirror that source; visuals stay client-side.
export const MEGATON_GACHA_CATALOG = buildCatalog();

const CATALOG_BY_ID = Object.freeze(Object.fromEntries(
  MEGATON_GACHA_CATALOG.map((item) => [item.id, item]),
));

export const MEGATON_PAID_INVENTORY_MAX_ITEMS = MEGATON_GACHA_CATALOG.length;

const CATALOG_BY_RARITY = Object.freeze(Object.fromEntries(
  RARITIES.map((rarity) => [
    rarity,
    Object.freeze(MEGATON_GACHA_CATALOG.filter((item) => item.rarity === rarity)),
  ]),
));

const PAID_PRODUCT_SPECS = Object.freeze({
  starter: Object.freeze({ rolls: 1, table: 'premium' }),
  arsenal_payload: Object.freeze({ rolls: 1, table: 'premium' }),
  arsenal_payload_10: Object.freeze({ rolls: 10, table: 'premium' }),
  arsenal_legendary_payload: Object.freeze({ rolls: 1, table: 'legendary_plus' }),
});

export const MEGATON_PAID_GACHA_PRODUCT_IDS = Object.freeze(Object.keys(PAID_PRODUCT_SPECS));
export const MEGATON_PAID_RECONCILE_LIMIT = 100;

const DROP_TABLES = Object.freeze({
  premium: Object.freeze([
    ['rare', 780000],
    ['epic', 160000],
    ['legendary', 52000],
    ['mythic', 8000],
  ]),
  legendary_plus: Object.freeze([
    ['legendary', 900000],
    ['mythic', 100000],
  ]),
});

export function paidGachaSpec(productId) {
  return PAID_PRODUCT_SPECS[String(productId || '')] || null;
}

export function secureRandomBelow(maxExclusive, cryptoApi = globalThis.crypto) {
  const max = Number(maxExclusive);
  if (!Number.isSafeInteger(max) || max <= 0 || max > 0x100000000) {
    throw new RangeError('invalid_secure_random_bound');
  }
  if (!cryptoApi || typeof cryptoApi.getRandomValues !== 'function') {
    throw new Error('secure_random_unavailable');
  }

  const range = 0x100000000;
  const limit = range - (range % max);
  const words = new Uint32Array(1);
  do {
    cryptoApi.getRandomValues(words);
  } while (words[0] >= limit);
  return words[0] % max;
}

function pickRarity(tableName, randomBelow) {
  const table = DROP_TABLES[tableName];
  if (!table) throw new Error('unknown_megaton_drop_table');
  let ticket = randomBelow(1000000);
  for (const [rarity, weight] of table) {
    if (ticket < weight) return rarity;
    ticket -= weight;
  }
  return table[table.length - 1][0];
}

export function rollMegatonPaidProduct(productId, randomBelow = secureRandomBelow) {
  const spec = paidGachaSpec(productId);
  if (!spec) return null;
  const rolls = [];
  for (let index = 0; index < spec.rolls; index += 1) {
    const rarity = pickRarity(spec.table, randomBelow);
    const pool = CATALOG_BY_RARITY[rarity];
    const item = pool[randomBelow(pool.length)];
    rolls.push({
      index,
      itemId: item.id,
      name: item.name,
      rarity: item.rarity,
      boost: { ...item.boost },
    });
  }
  return rolls;
}

export function paidPurchaseAmountMatches(purchase, product) {
  if (!purchase || !product || purchase.status !== 'paid') return false;
  const currency = String(purchase.currency || '').toUpperCase();
  if (currency === 'XTR') {
    return Number.isSafeInteger(Number(product.amount))
      && Number(purchase.total_amount) === Number(product.amount);
  }
  if (currency === 'TON' || currency === 'TON_CREDIT') {
    try {
      return BigInt(String(purchase.total_amount || '0')) === BigInt(String(product.nanotons || '0'));
    } catch {
      return false;
    }
  }
  return false;
}

export async function listPaidMegatonGachaPurchases(
  env,
  telegramUserId,
  cutoverAt,
  limit = MEGATON_PAID_RECONCILE_LIMIT,
) {
  const boundedLimit = Math.max(1, Math.min(
    MEGATON_PAID_RECONCILE_LIMIT,
    Math.floor(Number(limit) || MEGATON_PAID_RECONCILE_LIMIT),
  ));
  const rows = await supabaseRequest(env, 'rpc/list_unredeemed_megaton_paid_gacha', {
    method: 'POST',
    headers: { prefer: 'return=representation' },
    body: JSON.stringify({
      p_telegram_user_id: String(telegramUserId),
      p_cutover_at: String(cutoverAt),
      p_limit: boundedLimit,
    }),
  });
  return Array.isArray(rows) ? rows : [];
}

export async function redeemMegatonPaidGacha(env, purchase, proposedRolls, cutoverAt) {
  const rows = await supabaseRequest(env, 'rpc/redeem_megaton_paid_gacha', {
    method: 'POST',
    headers: { prefer: 'return=representation' },
    body: JSON.stringify({
      p_purchase_payload: purchase.payload,
      p_telegram_user_id: purchase.telegram_user_id,
      p_product_id: purchase.product_id,
      p_catalog_version: MEGATON_PAID_GACHA_CATALOG_VERSION,
      p_cutover_at: String(cutoverAt || ''),
      p_rolls: proposedRolls,
    }),
  });
  return Array.isArray(rows) && rows.length ? rows[0] : null;
}

function safeInventoryCounter(value, field) {
  let counter = null;
  if (typeof value === 'number' && Number.isSafeInteger(value) && value >= 0) {
    counter = value;
  } else if (typeof value === 'string' && /^(0|[1-9]\d*)$/.test(value)) {
    const parsed = BigInt(value);
    if (parsed <= BigInt(Number.MAX_SAFE_INTEGER)) counter = Number(parsed);
  }
  if (counter === null) {
    const error = new Error(`Invalid Megaton paid inventory ${field}`);
    error.code = 'invalid_paid_inventory_snapshot';
    throw error;
  }
  return counter;
}

function publicPaidInventoryRows(rows) {
  if (!Array.isArray(rows) || rows.length > MEGATON_PAID_INVENTORY_MAX_ITEMS) {
    const error = new Error('Invalid Megaton paid inventory row count');
    error.code = 'invalid_paid_inventory_snapshot';
    throw error;
  }

  const seen = new Set();
  return rows.map((row) => {
    const itemId = String(row && row.item_id || '');
    const rarity = String(row && row.rarity || '');
    const catalogItem = CATALOG_BY_ID[itemId];
    const paidCopies = safeInventoryCounter(row && row.paid_copies, 'paid_copies');
    if (!catalogItem || catalogItem.rarity !== rarity || paidCopies < 1 || seen.has(itemId)) {
      const error = new Error('Invalid Megaton paid inventory row');
      error.code = 'invalid_paid_inventory_snapshot';
      throw error;
    }
    seen.add(itemId);
    return { itemId, rarity, paidCopies };
  });
}

function publicPaidInventoryStats(rows, inventory) {
  if (!Array.isArray(rows) || rows.length > 1) {
    const error = new Error('Invalid Megaton paid inventory stats row count');
    error.code = 'invalid_paid_inventory_snapshot';
    throw error;
  }
  if (!rows.length) {
    if (inventory.length) {
      const error = new Error('Missing Megaton paid inventory stats');
      error.code = 'invalid_paid_inventory_snapshot';
      throw error;
    }
    return { totalPaidRolls: 0, uniquePaidItems: 0, duplicatePaidRolls: 0 };
  }

  const row = rows[0];
  const stats = {
    totalPaidRolls: safeInventoryCounter(row.total_paid_rolls, 'total_paid_rolls'),
    uniquePaidItems: safeInventoryCounter(row.unique_paid_items, 'unique_paid_items'),
    duplicatePaidRolls: safeInventoryCounter(row.duplicate_paid_rolls, 'duplicate_paid_rolls'),
  };
  let paidCopyTotal = 0;
  for (const item of inventory) {
    paidCopyTotal += item.paidCopies;
    if (!Number.isSafeInteger(paidCopyTotal)) {
      const error = new Error('Megaton paid inventory total exceeds safe integer range');
      error.code = 'invalid_paid_inventory_snapshot';
      throw error;
    }
  }
  if (
    stats.uniquePaidItems !== inventory.length
    || stats.totalPaidRolls !== paidCopyTotal
    || stats.uniquePaidItems + stats.duplicatePaidRolls !== stats.totalPaidRolls
  ) {
    const error = new Error('Inconsistent Megaton paid inventory stats');
    error.code = 'invalid_paid_inventory_snapshot';
    throw error;
  }
  return stats;
}

export async function getPaidMegatonInventorySnapshot(env, telegramUserId) {
  const inventoryParams = new URLSearchParams({
    select: 'item_id,rarity,paid_copies',
    telegram_user_id: `eq.${String(telegramUserId)}`,
    order: 'item_id.asc',
    limit: String(MEGATON_PAID_INVENTORY_MAX_ITEMS + 1),
  });
  const inventoryRows = await supabaseRequest(
    env,
    `telegram_megaton_paid_inventory?${inventoryParams.toString()}`,
    { method: 'GET' },
  );
  const inventory = publicPaidInventoryRows(inventoryRows);

  const statsParams = new URLSearchParams({
    select: 'total_paid_rolls,unique_paid_items,duplicate_paid_rolls',
    telegram_user_id: `eq.${String(telegramUserId)}`,
    limit: '1',
  });
  const statsRows = await supabaseRequest(
    env,
    `telegram_megaton_paid_inventory_stats?${statsParams.toString()}`,
    { method: 'GET' },
  );

  return {
    catalogVersion: MEGATON_PAID_GACHA_CATALOG_VERSION,
    items: inventory,
    stats: publicPaidInventoryStats(statsRows, inventory),
  };
}

export function publicPaidGachaReceipt(row) {
  if (!row) return null;
  return {
    receiptId: row.receipt_id,
    productId: row.product_id,
    catalogVersion: row.catalog_version,
    rolls: Array.isArray(row.rolls) ? row.rolls : [],
    rollCount: Number(row.roll_count || 0),
    createdAt: row.created_at,
    idempotent: Boolean(row.idempotent),
    payment: {
      currency: row.purchase_currency,
      totalAmount: String(row.purchase_total_amount || ''),
      paidAt: row.purchase_paid_at,
    },
    inventory: {
      totalPaidRolls: Number(row.total_paid_rolls || 0),
      uniquePaidItems: Number(row.unique_paid_items || 0),
      duplicatePaidRolls: Number(row.duplicate_paid_rolls || 0),
    },
  };
}
