// Token-gated publish-board data for admin.html (mirrors admin/stats.js auth).
//
// The data is BUNDLED from functions/_data/publish-status.js — generated by
// Shared/tools/games-master/build_dashboard.py (from status.json) and written
// there by Gallery/scripts/sync_games.sh. It lives under functions/ on purpose:
// Cloudflare Pages does NOT serve files inside functions/ as public static
// assets, so this internal pipeline state is only reachable WITH the admin
// token (unlike a public /publish-status.json, which robots.txt can't gate).
import publishData from "../../_data/publish-status.js";
import { requireAdmin } from "../../_lib/adminAuth.js";

function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json", "cache-control": "no-store" },
  });
}

export async function onRequestGet({ request, env }) {
  const guard = await requireAdmin(request, env);
  if (guard) return guard;
  return json(publishData);
}
