// Token-gated publish-board data for admin.html (mirrors admin/stats.js auth).
//
// The data is BUNDLED from functions/_data/publish-status.js — generated by
// Shared/tools/games-master/build_dashboard.py (from status.json) and written
// there by Gallery/scripts/sync_games.sh. It lives under functions/ on purpose:
// Cloudflare Pages does NOT serve files inside functions/ as public static
// assets, so this internal pipeline state is only reachable WITH the admin
// token (unlike a public /publish-status.json, which robots.txt can't gate).
import publishData from "../../_data/publish-status.js";

function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json", "cache-control": "no-store" },
  });
}

export async function onRequestGet({ request, env }) {
  const url = new URL(request.url);
  const token =
    url.searchParams.get("token") || request.headers.get("x-admin-token") || "";
  if (!env.ADMIN_TOKEN) {
    return json({ error: "admin_token_not_configured: set ADMIN_TOKEN in the Pages dashboard" }, 500);
  }
  if (token !== env.ADMIN_TOKEN) {
    return json({ error: "forbidden" }, 403);
  }
  return json(publishData);
}
